"""Rename user to user_id

Revision ID: 5d43eb9bfe78
Revises: e4598273c1db
Create Date: 2020-05-22 06:08:05.034334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5d43eb9bfe78"
down_revision = "e4598273c1db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("oauth2_code", "user", new_column_name="user_id")
    op.alter_column("oauth2_token", "user", new_column_name="user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("oauth2_code", "user_id", new_column_name="user")
    op.alter_column("oauth2_token", "user_id", new_column_name="user")
    # ### end Alembic commands ###
