"""Add Client.owner_id

Revision ID: dd58bc95a904
Revises: 5d43eb9bfe78
Create Date: 2020-05-25 17:55:05.506518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd58bc95a904"
down_revision = "5d43eb9bfe78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth2_client", sa.Column("owner_id", sa.String(length=40), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth2_client", "owner_id")
    # ### end Alembic commands ###
